site: qtguru
title: Qtguru
greetings: Salutations All 👋
description: >-
  Qtguru personal diary about freelancing, coding, and personal growth.
lang: en-US
timezone: US/Pacific
repo: https://github.com/dojovader # site repo [optional]
data-theme: dark # default theme "dark" | "light"
discus-identifier: # replace with your disqus shortname
comments-enabled: true # true to enable disqus comments, false to hide them

author:
  name: qtguru
  bio: just a minimalist, personal blog
  userpicture:
  username: # general username
  github: dojovader # github username
  twitter: qtguru# twitter username
  email: okeowoaderemi@gmail.com # email adress

# Font Settings
googlewebfonts: family=JetBrains+Mono:ital,wght@0,100..800;1,100..800

# URL settings
url: "https://dojovader.github.io" # Domain Name of host. [username].github.io for github pages
baseurl: "/" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty
google_analytics: G-2K2P5C1VVE

# local
# url: "http://localhost:4000" #
# baseurl: "" #

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled: true
  collections: false
