name: Okeowo Aderemi
description: Blogging about Technical Stuff and Rants
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: /
domain_name: "http://dojovader.github.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Okeowo Aderemi"

# Disqus config
disqus-shortname: "dojovader"
